FROM node:13.12.0-stretch

WORKDIR /app

EXPOSE 8888

RUN echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && \
    echo fs.inotify.max_user_watches=524288 | tee /etc/sysctl.d/40-max-user-watches.conf

# Add Tini for better and faster SIGTERM handling
ENV TINI_VERSION v0.19.0
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini
ENTRYPOINT ["/tini", "--"]

# Start Angular Universal in watch mode
CMD npm run tmp:cleanup && npx ng build --watch --deleteOutputPath=false
