FROM node:12-alpine

WORKDIR /app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install --no-audit

# Bundle app source
COPY . .

RUN npm run prerender

EXPOSE 4000

CMD ["node", "/app/dist/server/main.js"]
