language: php
php:
  - 5.6

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
 - travis_retry composer self-update && composer --version
 - travis_retry composer update --dev --prefer-dist --no-interaction
# codeception
 - travis_retry composer global require "codeception/codeception=2.0.*" "codeception/specify=*" "codeception/verify=*"
# setup application:
 - |
   php init --env=Development
   sed -i s/root/travis/ common/config/main-local.php
   sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" backend/config/main.php
   cd tests/codeception/common && codecept build
   cd ../console && codecept build
   cd ../rest && codecept build
   cd ../../../

before_script:
  - cd tests/codeception/bin && php yii migrate --interactive=0 && cd ../../..

script:
 - |
     php -S localhost:8080 > /dev/null 2>&1 &
     cd tests
     ./../vendor/bin/codecept run
