<?php
/**
 * Created by PhpStorm.
 * User: ubuntu
 * Date: 3/1/19
 * Time: 1:50 PM
 */

namespace fixtures;


use common\models\Audiobook;
use common\models\AudiobookAuthor;
use common\models\AudiobookCover;
use common\models\AudiobookMeta;
use common\models\Author;
use Faker\Factory;
use Faker\Generator;
use Yii;
use yii\test\ActiveFixture;



class AudiobookFixture extends ActiveFixture
{
    public $modelClass = Audiobook::class;
    public $depends = [
        AuthorFixture::class,
    ];

    /**
     * @var Generator
     */
    private $faker;
    public $dataCount = 1500;

    public function init()
    {
        parent::init();

        $this->faker = Factory::create();
    }

    public function load()
    {
        parent::load(); // TODO: Change the autogenerated stub
    }

    protected function getData()
    {
        $faker = Factory::create();

        $data = [];

        for ($i = 0; $i < $this->dataCount; $i++) {
            $data[] = [
                'title' => ucwords($faker->words(10, true)),
                'description' => $faker->realText(500),
                'language' => 'English',
                'copyright_year' => $faker->numberBetween(1600, 2019),
                'num_sections' => $faker->numberBetween(1, 99),
                'url_zip_file' => $faker->url,
                'totaltimesecs' => $faker->numberBetween(120, 999999999),
            ];
        }
        return $data;
    }

    public function afterLoad()
    {
        parent::afterLoad();

        $authors = Author::find()
                         ->all();

        // Attach the audiobooks to random authors
        foreach ($this->data as $i => $row) {
            $randomAuthor = $authors[array_rand($authors)];

            AudiobookAuthor::deleteAll(['id_book' => $row['id']]);

            $authorRelation = new AudiobookAuthor();
            $authorRelation->id_book = $row['id'];
            $authorRelation->id_author = $randomAuthor->id;
            $authorRelation->save(false);

            // Generate random cover image for audiobook
            $cover = new AudiobookCover();
            $cover->id_book = $row['id'];
            $cover->url = $this->faker->imageUrl();
            $cover->save(false);

        }
    }

    protected function resetTable()
    {
        parent::resetTable();

        Yii::$app->db->createCommand()
                     ->delete(AudiobookMeta::tableName())
                     ->execute();
    }
}
